name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: List the files in the working directory (for debugging purposes)
      - name: List working directory
        run: |
          ls -R
      
      # Step 3: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust Node.js version if needed

      # Step 4: Configure Git to allow large payloads (if necessary)
      - name: Configure Git
        run: |
          git config --global http.postBuffer 524288000  # 500 MB

      # Step 5: Install client (frontend) dependencies
      - name: Install client dependencies
        run: |
          cd client
          npm install
      
      # Step 6: Run client (frontend) tests
      - name: Run client tests
        run: |
          cd client
          npm test

      # Step 7: Build the client (frontend)
      - name: Build client
        run: |
          cd client
          npm run build
      
      # Step 8: Deploy to the server
      - name: Deploy to server
        run: |
          # Add your actual deployment command/script here
          echo "Deploying the application to the server..."
          # Example (rsync for deployment):
          # rsync -avz client/build/ user@your-server:/path/to/your/deployment/folder